In [64]:
import pandas as pd

In [65]:
df= pd.read_csv('testing.csv', header=None, names=['ID','Name','Age'], index_col=0,usecols=['ID','Name'])

In [66]:
df.head()

           Name
ID
1          Manu
2        Barath
3    Periyasamy
4   Kanakarajan
5      Balamani

In [67]:
df1=pd.read_csv('Testing_Csv.csv',sep='|',skiprows=2,header=None,names=['ID','Name','Age','DOB'],parse_dates=[3],dayfirst=True)
df1.head()

   ID    Name  Age         DOB
0   1    Manu   24  27-02-2002
1   2  Barath   25  29-02-2002

In [68]:
email_Ids=['manubarath33@gmail.com','barathmanu05@gmail.com']
df1['Email']=email_Ids

In [69]:
df1.head()

   ID    Name  Age         DOB                   Email
0   1    Manu   24  27-02-2002  manubarath33@gmail.com
1   2  Barath   25  29-02-2002  barathmanu05@gmail.com

In [70]:
LastName=['Kanakarajan','Balamani']

df1.insert(2,'LastName','LastName')

In [71]:
df1.head()

   ID    Name  LastName  Age         DOB                   Email
0   1    Manu  LastName   24  27-02-2002  manubarath33@gmail.com
1   2  Barath  LastName   25  29-02-2002  barathmanu05@gmail.com